# ============================================================
# Iterable 2-3-4 Tree - High-Level Notes
# ============================================================
#
# A 2-3-4 tree is a B-tree with minimum degree t = 2.
#
# A node may store:
#
#   1 key = 2-node
#   2 keys = 3-node
#   3 keys = 4-node
#
# An iterable tree can be used directly in a for loop:
#
#   for value in tree:
#       print(value)
#
# This iterator performs an inorder traversal and yields all
# values in sorted order.
#
#
# ============================================================
# TIME COMPLEXITY
# ============================================================
#
# Insert one value:
#
#   O(log n)
#
# Search or membership check:
#
#   O(log n)
#
# Iterate through the entire tree:
#
#   O(n)
#
# Each value is yielded exactly once during a complete inorder
# traversal.
#
#
# ============================================================
# SPACE COMPLEXITY
# ============================================================
#
# Entire tree:
#
#   O(n)
#
# Iterator recursion stack:
#
#   O(log n)
#
# Converting the iterator to a list:
#
#   O(n) additional space
#
# Normal iteration yields one value at a time and only keeps
# the root-to-current-node traversal path in memory.
#
# ============================================================
# ITERABLE 2-3-4 TREE IMPLEMENTATION
# ============================================================
class Tree234Node:
    def __init__(self, leaf=False):
        self.keys = []
        self.children = []
        self.leaf = leaf
#
#
class Iterable234Tree:
    def __init__(self):
        self.root = Tree234Node(leaf=True)
#
    def insert(self, key):
        root = self.root
#
        if len(root.keys) == 3:
            new_root = Tree234Node(leaf=False)
            new_root.children.append(root)
            self._split_child(new_root, 0)
            self.root = new_root
            self._insert_non_full(new_root, key)
        else:
            self._insert_non_full(root, key)
#
    def _insert_non_full(self, node, key):
        index = len(node.keys) - 1
#
        if node.leaf:
            node.keys.append(None)
#
            while index >= 0 and key < node.keys[index]:
                node.keys[index + 1] = node.keys[index]
                index -= 1
#
            node.keys[index + 1] = key
            return
#
        while index >= 0 and key < node.keys[index]:
            index -= 1
#
        child_index = index + 1
#
        if len(node.children[child_index].keys) == 3:
            self._split_child(node, child_index)
#
            if key > node.keys[child_index]:
                child_index += 1
#
        self._insert_non_full(node.children[child_index], key)
#
    def _split_child(self, parent, child_index):
        full_child = parent.children[child_index]
        right_child = Tree234Node(leaf=full_child.leaf)
#
        middle_key = full_child.keys[1]
        right_child.keys = [full_child.keys[2]]
        full_child.keys = [full_child.keys[0]]
#
        if not full_child.leaf:
            right_child.children = full_child.children[2:]
            full_child.children = full_child.children[:2]
#
        parent.keys.insert(child_index, middle_key)
        parent.children.insert(child_index + 1, right_child)
#
    def __iter__(self):
        # yield from returns every value generated by _inorder.
        yield from self._inorder(self.root)
#
    def _inorder(self, node):
        for index, key in enumerate(node.keys):
            if not node.leaf:
                yield from self._inorder(node.children[index])
#
            yield key
#
        if not node.leaf:
            yield from self._inorder(
                node.children[len(node.keys)]
            )
#
    def __contains__(self, key):
        return self.search(key)
#
    def search(self, key):
        current = self.root
#
        while True:
            index = 0
#
            while index < len(current.keys) and key > current.keys[index]:
                index += 1
#
            if index < len(current.keys) and current.keys[index] == key:
                return True
#
            if current.leaf:
                return False
#
            current = current.children[index]
#
    def display(self):
        current_level = [self.root]
        level = 0
#
        while current_level:
            next_level = []
            node_text = []
#
            for node in current_level:
                node_text.append(str(node.keys))
                next_level.extend(node.children)
#
            print(f"Level {level}: " + " | ".join(node_text))
            current_level = next_level
            level += 1
#
#
# ============================================================
# CODE EXAMPLE
# ============================================================
tree = Iterable234Tree()
values = [40, 10, 60, 20, 50, 70, 30, 5]
#
for value in values:
    tree.insert(value)
#
print("=" * 60)
print("2-3-4 TREE STRUCTURE")
print("=" * 60)
tree.display()
#
print("\n" + "=" * 60)
print("ITERATION IN SORTED ORDER")
print("=" * 60)
#
for value in tree:
    print(value)
#
print("\nTree as a list:", list(tree))
print("50 in tree:", 50 in tree)
print("99 in tree:", 99 in tree)

